export const WorkspacePermissions = {
  CREATE_WORKSPACE: "CREATE_WORKSPACE",
  EDIT_WORKSPACE: "EDIT_WORKSPACE",
  DELETE_WORKSPACE: "DELETE_WORKSPACE",
  MANAGE_WORKSPACE_SETTINGS: "MANAGE_WORKSPACE_SETTINGS",

  ADD_WORKSPACE_MEMBER: "ADD_WORKSPACE_MEMBER",
  CHANGE_WORKSPACE_MEMBER_ROLE: "CHANGE_WORKSPACE_MEMBER_ROLE",
  REMOVE_WORKSPACE_MEMBER: "REMOVE_WORKSPACE_MEMBER",

  CREATE_BOARD: "CREATE_BOARD",
  VIEW_ALL_BOARDS: "VIEW_ALL_BOARDS",
  VIEW_ONLY: "VIEW_ONLY",
} as const;

export type WorkspacePermissionsType = keyof typeof WorkspacePermissions;
