export const WorkspacePermissions = {
  CREATE_WORKSPACE: "CREATE_WORKSPACE",
  EDIT_WORKSPACE: "EDIT_WORKSPACE",
  DELETE_WORKSPACE: "DELETE_WORKSPACE",
  MANAGE_WORKSPACE_SETTINGS: "MANAGE_WORKSPACE_SETTINGS",

  ADD_WORKSPACE_MEMBER: "ADD_WORKSPACE_MEMBER",
  CHANGE_WORKSPACE_MEMBER_ROLE: "CHANGE_WORKSPACE_MEMBER_ROLE",
  REMOVE_WORKSPACE_MEMBER: "REMOVE_WORKSPACE_MEMBER",

  CREATE_BOARD: "CREATE_BOARD",
  VIEW_ALL_BOARDS: "VIEW_ALL_BOARDS",
  VIEW_ONLY: "VIEW_ONLY",
} as const;

export type WorkspacePermissionsType = keyof typeof WorkspacePermissions;

export const BoardPermissions = {
  VIEW_BOARD: "VIEW_BOARD",
  EDIT_BOARD: "EDIT_BOARD",

  VIEW_BOARD_MEMBERS: "VIEW_BOARD_MEMBERS",
  ADD_BOARD_MEMBER: "ADD_BOARD_MEMBER",
  CHANGE_BOARD_MEMBER_ROLE: "CHANGE_BOARD_MEMBER_ROLE",
  REMOVE_BOARD_MEMBER: "REMOVE_BOARD_MEMBER",

  VIEW_LIST: "VIEW_LIST",
  CREATE_LIST: "CREATE_LIST",
  EDIT_LIST: "EDIT_LIST",
  DELETE_LIST: "DELETE_LIST",

  CREATE_CARD: "CREATE_CARD",
  EDIT_CARD: "EDIT_CARD",
  DELETE_CARD: "DELETE_CARD",
  ADD_CARD_MEMBER: "ADD_CARD_MEMBER",
  REMOVE_CARD_MEMBER: "REMOVE_CARD_MEMBER",
  ADD_CARD_LABELS: "ADD_CARD_LABELS",
  DELETE_CARD_LABELS: "DELETE_CARD_LABELS",
  CHANGE_CARD_DUE_DATE: "CHANGE_CARD_DUE_DATE",

  CREATE_CHECKITEM: "CREATE_CHECKITEM",
  UPDATE_CHECKITEM: "UPDATE_CHECKITEM",
  DELETE_CHECKITEM: "DELETE_CHECKITEM",
  ASSIGN_CHECKITEM_TO_CARD_MEMBER: "ASSIGN_CHECKITEM_TO_CARD_MEMBER",
} as const;

export type BoardPermissionsType = keyof typeof BoardPermissions;
