export const BoardRoles = {
  BOARD_ADMIN: "BOARD_ADMIN",
  BOARD_MEMBER: "BOARD_MEMBER",
} as const;

export type BoardRoleType = keyof typeof BoardRoles;

export const BoardPermissions = {
  VIEW_BOARD: "VIEW_BOARD",
  EDIT_BOARD: "EDIT_BOARD",

  VIEW_BOARD_MEMBERS: "VIEW_BOARD_MEMBERS",
  ADD_BOARD_MEMBER: "ADD_BOARD_MEMBER",
  CHANGE_BOARD_MEMBER_ROLE: "CHANGE_BOARD_MEMBER_ROLE",
  REMOVE_BOARD_MEMBER: "REMOVE_BOARD_MEMBER",

  VIEW_LIST: "VIEW_LIST",
  CREATE_LIST: "CREATE_LIST",
  EDIT_LIST: "EDIT_LIST",
  DELETE_LIST: "DELETE_LIST",

  CREATE_CARD: "CREATE_CARD",
  EDIT_CARD: "EDIT_CARD",
  DELETE_CARD: "DELETE_CARD",

  VIEW_CARD: "VIEW_CARD",
  ADD_CARD_MEMBER: "ADD_CARD_MEMBER",
  REMOVE_CARD_MEMBER: "REMOVE_CARD_MEMBER",
  ADD_CARD_LABELS: "ADD_CARD_LABELS",
  DELETE_CARD_LABELS: "DELETE_CARD_LABELS",
  CHANGE_CARD_DUE_DATE: "CHANGE_CARD_DUE_DATE",

  CREATE_CHECKITEM: "CREATE_CHECKITEM",
  UPDATE_CHECKITEM: "UPDATE_CHECKITEM",
  DELETE_CHECKITEM: "DELETE_CHECKITEM",
  ASSIGN_CHECKITEM_TO_CARD_MEMBER: "ASSIGN_CHECKITEM_TO_CARD_MEMBER",
} as const;

export type BoardPermissionType = keyof typeof BoardPermissions;
